# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UseCaseForm.ui'
#
# Created: Thu May  9 16:07:11 2013
#      by: PyQt4 UI code generator 4.9.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_UseCaseForm(object):
    def setupUi(self, UseCaseForm):
        UseCaseForm.setObjectName(_fromUtf8("UseCaseForm"))
        UseCaseForm.resize(648, 610)
        self.verticalLayout = QtGui.QVBoxLayout(UseCaseForm)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.titleLabel = QtGui.QLabel(UseCaseForm)
        self.titleLabel.setObjectName(_fromUtf8("titleLabel"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.titleLabel)
        self.titleEdit = QtGui.QLineEdit(UseCaseForm)
        self.titleEdit.setObjectName(_fromUtf8("titleEdit"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.titleEdit)
        self.idLabel = QtGui.QLabel(UseCaseForm)
        self.idLabel.setObjectName(_fromUtf8("idLabel"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.idLabel)
        self.idEdit = QtGui.QLineEdit(UseCaseForm)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.idEdit.sizePolicy().hasHeightForWidth())
        self.idEdit.setSizePolicy(sizePolicy)
        self.idEdit.setObjectName(_fromUtf8("idEdit"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.idEdit)
        self.actorMainLabel = QtGui.QLabel(UseCaseForm)
        self.actorMainLabel.setObjectName(_fromUtf8("actorMainLabel"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.actorMainLabel)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.actorMainEdit = QtGui.QLineEdit(UseCaseForm)
        self.actorMainEdit.setEnabled(True)
        self.actorMainEdit.setReadOnly(True)
        self.actorMainEdit.setObjectName(_fromUtf8("actorMainEdit"))
        self.horizontalLayout.addWidget(self.actorMainEdit)
        self.actorMainSelectButton = QtGui.QPushButton(UseCaseForm)
        self.actorMainSelectButton.setObjectName(_fromUtf8("actorMainSelectButton"))
        self.horizontalLayout.addWidget(self.actorMainSelectButton)
        self.formLayout.setLayout(2, QtGui.QFormLayout.FieldRole, self.horizontalLayout)
        self.actorOtherLabel = QtGui.QLabel(UseCaseForm)
        self.actorOtherLabel.setObjectName(_fromUtf8("actorOtherLabel"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.actorOtherLabel)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.actorOtherEdit = QtGui.QLineEdit(UseCaseForm)
        self.actorOtherEdit.setEnabled(True)
        self.actorOtherEdit.setReadOnly(True)
        self.actorOtherEdit.setObjectName(_fromUtf8("actorOtherEdit"))
        self.horizontalLayout_2.addWidget(self.actorOtherEdit)
        self.actorOthersSelectButton = QtGui.QPushButton(UseCaseForm)
        self.actorOthersSelectButton.setObjectName(_fromUtf8("actorOthersSelectButton"))
        self.horizontalLayout_2.addWidget(self.actorOthersSelectButton)
        self.formLayout.setLayout(3, QtGui.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.verticalLayout.addLayout(self.formLayout)
        self.tabWidget = QtGui.QTabWidget(UseCaseForm)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_1 = QtGui.QWidget()
        self.tab_1.setObjectName(_fromUtf8("tab_1"))
        self.formLayout_3 = QtGui.QFormLayout(self.tab_1)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.priorityLabel = QtGui.QLabel(self.tab_1)
        self.priorityLabel.setObjectName(_fromUtf8("priorityLabel"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.priorityLabel)
        self.priorityComboBox = QtGui.QComboBox(self.tab_1)
        self.priorityComboBox.setObjectName(_fromUtf8("priorityComboBox"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.priorityComboBox)
        self.goalLevelLabel = QtGui.QLabel(self.tab_1)
        self.goalLevelLabel.setObjectName(_fromUtf8("goalLevelLabel"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.goalLevelLabel)
        self.goalLevelComboBox = QtGui.QComboBox(self.tab_1)
        self.goalLevelComboBox.setObjectName(_fromUtf8("goalLevelComboBox"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.goalLevelComboBox)
        self.tabWidget.addTab(self.tab_1, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.formLayout_2 = QtGui.QFormLayout(self.tab_2)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.scenarioLabel = QtGui.QLabel(self.tab_2)
        self.scenarioLabel.setObjectName(_fromUtf8("scenarioLabel"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.scenarioLabel)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.mainScenarioView = QtGui.QTableView(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainScenarioView.sizePolicy().hasHeightForWidth())
        self.mainScenarioView.setSizePolicy(sizePolicy)
        self.mainScenarioView.setObjectName(_fromUtf8("mainScenarioView"))
        self.horizontalLayout_3.addWidget(self.mainScenarioView)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.insertStepMSButton = QtGui.QPushButton(self.tab_2)
        self.insertStepMSButton.setObjectName(_fromUtf8("insertStepMSButton"))
        self.verticalLayout_2.addWidget(self.insertStepMSButton)
        self.addEventMSButton = QtGui.QPushButton(self.tab_2)
        self.addEventMSButton.setObjectName(_fromUtf8("addEventMSButton"))
        self.verticalLayout_2.addWidget(self.addEventMSButton)
        self.deleteMSButton = QtGui.QPushButton(self.tab_2)
        self.deleteMSButton.setObjectName(_fromUtf8("deleteMSButton"))
        self.verticalLayout_2.addWidget(self.deleteMSButton)
        self.moveUpMSButton = QtGui.QPushButton(self.tab_2)
        self.moveUpMSButton.setObjectName(_fromUtf8("moveUpMSButton"))
        self.verticalLayout_2.addWidget(self.moveUpMSButton)
        self.moveDownMSButton = QtGui.QPushButton(self.tab_2)
        self.moveDownMSButton.setObjectName(_fromUtf8("moveDownMSButton"))
        self.verticalLayout_2.addWidget(self.moveDownMSButton)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.formLayout_2.setLayout(0, QtGui.QFormLayout.FieldRole, self.horizontalLayout_3)
        self.label = QtGui.QLabel(self.tab_2)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.eventsView = QtGui.QTableView(self.tab_2)
        self.eventsView.setObjectName(_fromUtf8("eventsView"))
        self.horizontalLayout_4.addWidget(self.eventsView)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.insertStepEvButton = QtGui.QPushButton(self.tab_2)
        self.insertStepEvButton.setObjectName(_fromUtf8("insertStepEvButton"))
        self.verticalLayout_3.addWidget(self.insertStepEvButton)
        self.deleteEvButton = QtGui.QPushButton(self.tab_2)
        self.deleteEvButton.setObjectName(_fromUtf8("deleteEvButton"))
        self.verticalLayout_3.addWidget(self.deleteEvButton)
        self.moveUpEvButton = QtGui.QPushButton(self.tab_2)
        self.moveUpEvButton.setObjectName(_fromUtf8("moveUpEvButton"))
        self.verticalLayout_3.addWidget(self.moveUpEvButton)
        self.moveDownEvButton = QtGui.QPushButton(self.tab_2)
        self.moveDownEvButton.setObjectName(_fromUtf8("moveDownEvButton"))
        self.verticalLayout_3.addWidget(self.moveDownEvButton)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.horizontalLayout_4.addLayout(self.verticalLayout_3)
        self.formLayout_2.setLayout(1, QtGui.QFormLayout.FieldRole, self.horizontalLayout_4)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.formLayout_4 = QtGui.QFormLayout(self.tab_3)
        self.formLayout_4.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_4.setObjectName(_fromUtf8("formLayout_4"))
        self.label_2 = QtGui.QLabel(self.tab_3)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_2)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.tableView = QtGui.QTableView(self.tab_3)
        self.tableView.setObjectName(_fromUtf8("tableView"))
        self.horizontalLayout_5.addWidget(self.tableView)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.pushButton = QtGui.QPushButton(self.tab_3)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.verticalLayout_4.addWidget(self.pushButton)
        self.pushButton_2 = QtGui.QPushButton(self.tab_3)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.verticalLayout_4.addWidget(self.pushButton_2)
        self.pushButton_5 = QtGui.QPushButton(self.tab_3)
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.verticalLayout_4.addWidget(self.pushButton_5)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem2)
        self.horizontalLayout_5.addLayout(self.verticalLayout_4)
        self.formLayout_4.setLayout(0, QtGui.QFormLayout.FieldRole, self.horizontalLayout_5)
        self.label_3 = QtGui.QLabel(self.tab_3)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_3)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.tableView_2 = QtGui.QTableView(self.tab_3)
        self.tableView_2.setObjectName(_fromUtf8("tableView_2"))
        self.horizontalLayout_6.addWidget(self.tableView_2)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.pushButton_3 = QtGui.QPushButton(self.tab_3)
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.verticalLayout_5.addWidget(self.pushButton_3)
        self.pushButton_6 = QtGui.QPushButton(self.tab_3)
        self.pushButton_6.setObjectName(_fromUtf8("pushButton_6"))
        self.verticalLayout_5.addWidget(self.pushButton_6)
        self.pushButton_7 = QtGui.QPushButton(self.tab_3)
        self.pushButton_7.setObjectName(_fromUtf8("pushButton_7"))
        self.verticalLayout_5.addWidget(self.pushButton_7)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem3)
        self.horizontalLayout_6.addLayout(self.verticalLayout_5)
        self.formLayout_4.setLayout(1, QtGui.QFormLayout.FieldRole, self.horizontalLayout_6)
        self.label_4 = QtGui.QLabel(self.tab_3)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_4)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.tableView_3 = QtGui.QTableView(self.tab_3)
        self.tableView_3.setObjectName(_fromUtf8("tableView_3"))
        self.horizontalLayout_7.addWidget(self.tableView_3)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.pushButton_4 = QtGui.QPushButton(self.tab_3)
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.verticalLayout_6.addWidget(self.pushButton_4)
        self.pushButton_8 = QtGui.QPushButton(self.tab_3)
        self.pushButton_8.setObjectName(_fromUtf8("pushButton_8"))
        self.verticalLayout_6.addWidget(self.pushButton_8)
        self.pushButton_9 = QtGui.QPushButton(self.tab_3)
        self.pushButton_9.setObjectName(_fromUtf8("pushButton_9"))
        self.verticalLayout_6.addWidget(self.pushButton_9)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem4)
        self.horizontalLayout_7.addLayout(self.verticalLayout_6)
        self.formLayout_4.setLayout(2, QtGui.QFormLayout.FieldRole, self.horizontalLayout_7)
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget)
        self.buttonBox = QtGui.QDialogButtonBox(UseCaseForm)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(UseCaseForm)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(UseCaseForm)

    def retranslateUi(self, UseCaseForm):
        UseCaseForm.setWindowTitle(QtGui.QApplication.translate("UseCaseForm", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.titleLabel.setText(QtGui.QApplication.translate("UseCaseForm", "Title", None, QtGui.QApplication.UnicodeUTF8))
        self.idLabel.setText(QtGui.QApplication.translate("UseCaseForm", "ID", None, QtGui.QApplication.UnicodeUTF8))
        self.actorMainLabel.setText(QtGui.QApplication.translate("UseCaseForm", "Main actor", None, QtGui.QApplication.UnicodeUTF8))
        self.actorMainSelectButton.setText(QtGui.QApplication.translate("UseCaseForm", "Select", None, QtGui.QApplication.UnicodeUTF8))
        self.actorOtherLabel.setText(QtGui.QApplication.translate("UseCaseForm", "Other actors", None, QtGui.QApplication.UnicodeUTF8))
        self.actorOthersSelectButton.setText(QtGui.QApplication.translate("UseCaseForm", "Select", None, QtGui.QApplication.UnicodeUTF8))
        self.priorityLabel.setText(QtGui.QApplication.translate("UseCaseForm", "Priority", None, QtGui.QApplication.UnicodeUTF8))
        self.goalLevelLabel.setText(QtGui.QApplication.translate("UseCaseForm", "Goal level", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), QtGui.QApplication.translate("UseCaseForm", "Properties", None, QtGui.QApplication.UnicodeUTF8))
        self.scenarioLabel.setText(QtGui.QApplication.translate("UseCaseForm", "Scenario", None, QtGui.QApplication.UnicodeUTF8))
        self.insertStepMSButton.setText(QtGui.QApplication.translate("UseCaseForm", "Insert step", None, QtGui.QApplication.UnicodeUTF8))
        self.addEventMSButton.setText(QtGui.QApplication.translate("UseCaseForm", "Add event", None, QtGui.QApplication.UnicodeUTF8))
        self.deleteMSButton.setText(QtGui.QApplication.translate("UseCaseForm", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.moveUpMSButton.setText(QtGui.QApplication.translate("UseCaseForm", "Move up", None, QtGui.QApplication.UnicodeUTF8))
        self.moveDownMSButton.setText(QtGui.QApplication.translate("UseCaseForm", "Move down", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("UseCaseForm", "Events", None, QtGui.QApplication.UnicodeUTF8))
        self.insertStepEvButton.setText(QtGui.QApplication.translate("UseCaseForm", "Insert step", None, QtGui.QApplication.UnicodeUTF8))
        self.deleteEvButton.setText(QtGui.QApplication.translate("UseCaseForm", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.moveUpEvButton.setText(QtGui.QApplication.translate("UseCaseForm", "Move up", None, QtGui.QApplication.UnicodeUTF8))
        self.moveDownEvButton.setText(QtGui.QApplication.translate("UseCaseForm", "Move down", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("UseCaseForm", "Scenario", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("UseCaseForm", "Triggers", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("UseCaseForm", "PushButton", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_2.setText(QtGui.QApplication.translate("UseCaseForm", "PushButton", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_5.setText(QtGui.QApplication.translate("UseCaseForm", "PushButton", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("UseCaseForm", "Preconditions", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_3.setText(QtGui.QApplication.translate("UseCaseForm", "PushButton", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_6.setText(QtGui.QApplication.translate("UseCaseForm", "PushButton", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_7.setText(QtGui.QApplication.translate("UseCaseForm", "PushButton", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("UseCaseForm", "Postconditions", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_4.setText(QtGui.QApplication.translate("UseCaseForm", "PushButton", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_8.setText(QtGui.QApplication.translate("UseCaseForm", "PushButton", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_9.setText(QtGui.QApplication.translate("UseCaseForm", "PushButton", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtGui.QApplication.translate("UseCaseForm", "Conditions", None, QtGui.QApplication.UnicodeUTF8))

